---
abstract: 'Obtain uploaded CPAN modules via NNTP.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
  Test::POE::Server::TCP: 0.12
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox-Uploads-NNTP
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Email::Simple: 2.003
  POE: 0.38
  POE::Component::Client::NNTP: 2.1
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
