---
abstract: 'Obtain uploaded CPAN modules via NNTP.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
  Test::POE::Server::TCP: 0.12
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-SmokeBox-Uploads-NNTP
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::SmokeBox::Uploads::NNTP:
    file: lib/POE/Component/SmokeBox/Uploads/NNTP.pm
    version: 1.00
requires:
  Email::Simple: 2.003
  POE: 0.38
  POE::Component::Client::NNTP: 2.1
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-smokebox-uploads-nntp/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-smokebox-uploads-nntp.git
version: 1.00
