---
abstract: 'Obtain uploaded CPAN modules via NNTP.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.71'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Component-SmokeBox-Uploads-NNTP
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Email::Simple: 2.003
  POE: 0.38
  POE::Component::Client::NNTP: 2.04
version: 0.04
